// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kv.proto

#include "kv.pb.h"
#include "kv.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace raftkv {
namespace kv {

static const char* KvService_method_names[] = {
  "/raftkv.kv.KvService/Get",
  "/raftkv.kv.KvService/PutAppend",
};

std::unique_ptr< KvService::Stub> KvService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< KvService::Stub> stub(new KvService::Stub(channel));
  return stub;
}

KvService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Get_(KvService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PutAppend_(KvService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status KvService::Stub::Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::raftkv::kv::GetReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Get_, context, request, response);
}

void KvService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void KvService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::GetReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void KvService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

void KvService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::GetReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raftkv::kv::GetReply>* KvService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::raftkv::kv::GetReply>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::raftkv::kv::GetReply>* KvService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::raftkv::kv::GetReply>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, false);
}

::grpc::Status KvService::Stub::PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::raftkv::kv::PutAppendReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PutAppend_, context, request, response);
}

void KvService::Stub::experimental_async::PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PutAppend_, context, request, response, std::move(f));
}

void KvService::Stub::experimental_async::PutAppend(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::PutAppendReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PutAppend_, context, request, response, std::move(f));
}

void KvService::Stub::experimental_async::PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PutAppend_, context, request, response, reactor);
}

void KvService::Stub::experimental_async::PutAppend(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::PutAppendReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PutAppend_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::raftkv::kv::PutAppendReply>* KvService::Stub::AsyncPutAppendRaw(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::raftkv::kv::PutAppendReply>::Create(channel_.get(), cq, rpcmethod_PutAppend_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::raftkv::kv::PutAppendReply>* KvService::Stub::PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::raftkv::kv::PutAppendReply>::Create(channel_.get(), cq, rpcmethod_PutAppend_, context, request, false);
}

KvService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KvService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KvService::Service, ::raftkv::kv::GetRequest, ::raftkv::kv::GetReply>(
          [](KvService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::raftkv::kv::GetRequest* req,
             ::raftkv::kv::GetReply* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      KvService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< KvService::Service, ::raftkv::kv::PutAppendRequest, ::raftkv::kv::PutAppendReply>(
          [](KvService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::raftkv::kv::PutAppendRequest* req,
             ::raftkv::kv::PutAppendReply* resp) {
               return service->PutAppend(ctx, req, resp);
             }, this)));
}

KvService::Service::~Service() {
}

::grpc::Status KvService::Service::Get(::grpc::ServerContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KvService::Service::PutAppend(::grpc::ServerContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace raftkv
}  // namespace kv

