// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kv.proto
#ifndef GRPC_kv_2eproto__INCLUDED
#define GRPC_kv_2eproto__INCLUDED

#include "kv.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace raftkv {
namespace kv {

// ── KV service (client-facing) ──────────────────────────────────
class KvService final {
 public:
  static constexpr char const* service_full_name() {
    return "raftkv.kv.KvService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::raftkv::kv::GetReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::GetReply>> AsyncGet(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::GetReply>>(AsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::GetReply>> PrepareAsyncGet(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::GetReply>>(PrepareAsyncGetRaw(context, request, cq));
    }
    virtual ::grpc::Status PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::raftkv::kv::PutAppendReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::PutAppendReply>> AsyncPutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::PutAppendReply>>(AsyncPutAppendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::PutAppendReply>> PrepareAsyncPutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::PutAppendReply>>(PrepareAsyncPutAppendRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::GetReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::GetReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::GetReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PutAppend(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::PutAppendReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PutAppend(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::PutAppendReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void PutAppend(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::PutAppendReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::GetReply>* AsyncGetRaw(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::GetReply>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::PutAppendReply>* AsyncPutAppendRaw(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::raftkv::kv::PutAppendReply>* PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::raftkv::kv::GetReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raftkv::kv::GetReply>> AsyncGet(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raftkv::kv::GetReply>>(AsyncGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raftkv::kv::GetReply>> PrepareAsyncGet(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raftkv::kv::GetReply>>(PrepareAsyncGetRaw(context, request, cq));
    }
    ::grpc::Status PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::raftkv::kv::PutAppendReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raftkv::kv::PutAppendReply>> AsyncPutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raftkv::kv::PutAppendReply>>(AsyncPutAppendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raftkv::kv::PutAppendReply>> PrepareAsyncPutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::raftkv::kv::PutAppendReply>>(PrepareAsyncPutAppendRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response, std::function<void(::grpc::Status)>) override;
      void Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::GetReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Get(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::GetReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::GetReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response, std::function<void(::grpc::Status)>) override;
      void PutAppend(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::PutAppendReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PutAppend(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PutAppend(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::PutAppendReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void PutAppend(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::raftkv::kv::PutAppendReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::raftkv::kv::GetReply>* AsyncGetRaw(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raftkv::kv::GetReply>* PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::raftkv::kv::GetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raftkv::kv::PutAppendReply>* AsyncPutAppendRaw(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::raftkv::kv::PutAppendReply>* PrepareAsyncPutAppendRaw(::grpc::ClientContext* context, const ::raftkv::kv::PutAppendRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Get_;
    const ::grpc::internal::RpcMethod rpcmethod_PutAppend_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Get(::grpc::ServerContext* context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response);
    virtual ::grpc::Status PutAppend(::grpc::ServerContext* context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Get() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raftkv::kv::GetRequest* /*request*/, ::raftkv::kv::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::raftkv::kv::GetRequest* request, ::grpc::ServerAsyncResponseWriter< ::raftkv::kv::GetReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PutAppend() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raftkv::kv::PutAppendRequest* /*request*/, ::raftkv::kv::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutAppend(::grpc::ServerContext* context, ::raftkv::kv::PutAppendRequest* request, ::grpc::ServerAsyncResponseWriter< ::raftkv::kv::PutAppendReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Get<WithAsyncMethod_PutAppend<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Get() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::raftkv::kv::GetRequest, ::raftkv::kv::GetReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::raftkv::kv::GetRequest* request, ::raftkv::kv::GetReply* response) { return this->Get(context, request, response); }));}
    void SetMessageAllocatorFor_Get(
        ::grpc::experimental::MessageAllocator< ::raftkv::kv::GetRequest, ::raftkv::kv::GetReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::raftkv::kv::GetRequest, ::raftkv::kv::GetReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raftkv::kv::GetRequest* /*request*/, ::raftkv::kv::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::raftkv::kv::GetRequest* /*request*/, ::raftkv::kv::GetReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Get(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::raftkv::kv::GetRequest* /*request*/, ::raftkv::kv::GetReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PutAppend() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::raftkv::kv::PutAppendRequest, ::raftkv::kv::PutAppendReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::raftkv::kv::PutAppendRequest* request, ::raftkv::kv::PutAppendReply* response) { return this->PutAppend(context, request, response); }));}
    void SetMessageAllocatorFor_PutAppend(
        ::grpc::experimental::MessageAllocator< ::raftkv::kv::PutAppendRequest, ::raftkv::kv::PutAppendReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::raftkv::kv::PutAppendRequest, ::raftkv::kv::PutAppendReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raftkv::kv::PutAppendRequest* /*request*/, ::raftkv::kv::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PutAppend(
      ::grpc::CallbackServerContext* /*context*/, const ::raftkv::kv::PutAppendRequest* /*request*/, ::raftkv::kv::PutAppendReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PutAppend(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::raftkv::kv::PutAppendRequest* /*request*/, ::raftkv::kv::PutAppendReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Get<ExperimentalWithCallbackMethod_PutAppend<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Get<ExperimentalWithCallbackMethod_PutAppend<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Get() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raftkv::kv::GetRequest* /*request*/, ::raftkv::kv::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PutAppend() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raftkv::kv::PutAppendRequest* /*request*/, ::raftkv::kv::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Get() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raftkv::kv::GetRequest* /*request*/, ::raftkv::kv::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PutAppend() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raftkv::kv::PutAppendRequest* /*request*/, ::raftkv::kv::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutAppend(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Get() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Get(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raftkv::kv::GetRequest* /*request*/, ::raftkv::kv::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Get(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Get(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PutAppend() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PutAppend(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raftkv::kv::PutAppendRequest* /*request*/, ::raftkv::kv::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* PutAppend(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* PutAppend(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Get : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Get() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raftkv::kv::GetRequest, ::raftkv::kv::GetReply>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::raftkv::kv::GetRequest, ::raftkv::kv::GetReply>* streamer) {
                       return this->StreamedGet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Get() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Get(::grpc::ServerContext* /*context*/, const ::raftkv::kv::GetRequest* /*request*/, ::raftkv::kv::GetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raftkv::kv::GetRequest,::raftkv::kv::GetReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PutAppend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PutAppend() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::raftkv::kv::PutAppendRequest, ::raftkv::kv::PutAppendReply>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::raftkv::kv::PutAppendRequest, ::raftkv::kv::PutAppendReply>* streamer) {
                       return this->StreamedPutAppend(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PutAppend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PutAppend(::grpc::ServerContext* /*context*/, const ::raftkv::kv::PutAppendRequest* /*request*/, ::raftkv::kv::PutAppendReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPutAppend(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::raftkv::kv::PutAppendRequest,::raftkv::kv::PutAppendReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_PutAppend<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_PutAppend<Service > > StreamedService;
};

}  // namespace kv
}  // namespace raftkv


#endif  // GRPC_kv_2eproto__INCLUDED
