// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

#ifndef PROTOBUF_INCLUDED_raft_2eproto
#define PROTOBUF_INCLUDED_raft_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_raft_2eproto 

namespace protobuf_raft_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[10];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_raft_2eproto
namespace raftkv {
namespace raft {
class AppendEntriesReply;
class AppendEntriesReplyDefaultTypeInternal;
extern AppendEntriesReplyDefaultTypeInternal _AppendEntriesReply_default_instance_;
class AppendEntriesRequest;
class AppendEntriesRequestDefaultTypeInternal;
extern AppendEntriesRequestDefaultTypeInternal _AppendEntriesRequest_default_instance_;
class GetStatusReply;
class GetStatusReplyDefaultTypeInternal;
extern GetStatusReplyDefaultTypeInternal _GetStatusReply_default_instance_;
class GetStatusRequest;
class GetStatusRequestDefaultTypeInternal;
extern GetStatusRequestDefaultTypeInternal _GetStatusRequest_default_instance_;
class InstallSnapshotReply;
class InstallSnapshotReplyDefaultTypeInternal;
extern InstallSnapshotReplyDefaultTypeInternal _InstallSnapshotReply_default_instance_;
class InstallSnapshotRequest;
class InstallSnapshotRequestDefaultTypeInternal;
extern InstallSnapshotRequestDefaultTypeInternal _InstallSnapshotRequest_default_instance_;
class LogEntry;
class LogEntryDefaultTypeInternal;
extern LogEntryDefaultTypeInternal _LogEntry_default_instance_;
class RaftPersistState;
class RaftPersistStateDefaultTypeInternal;
extern RaftPersistStateDefaultTypeInternal _RaftPersistState_default_instance_;
class RequestVoteReply;
class RequestVoteReplyDefaultTypeInternal;
extern RequestVoteReplyDefaultTypeInternal _RequestVoteReply_default_instance_;
class RequestVoteRequest;
class RequestVoteRequestDefaultTypeInternal;
extern RequestVoteRequestDefaultTypeInternal _RequestVoteRequest_default_instance_;
}  // namespace raft
}  // namespace raftkv
namespace google {
namespace protobuf {
template<> ::raftkv::raft::AppendEntriesReply* Arena::CreateMaybeMessage<::raftkv::raft::AppendEntriesReply>(Arena*);
template<> ::raftkv::raft::AppendEntriesRequest* Arena::CreateMaybeMessage<::raftkv::raft::AppendEntriesRequest>(Arena*);
template<> ::raftkv::raft::GetStatusReply* Arena::CreateMaybeMessage<::raftkv::raft::GetStatusReply>(Arena*);
template<> ::raftkv::raft::GetStatusRequest* Arena::CreateMaybeMessage<::raftkv::raft::GetStatusRequest>(Arena*);
template<> ::raftkv::raft::InstallSnapshotReply* Arena::CreateMaybeMessage<::raftkv::raft::InstallSnapshotReply>(Arena*);
template<> ::raftkv::raft::InstallSnapshotRequest* Arena::CreateMaybeMessage<::raftkv::raft::InstallSnapshotRequest>(Arena*);
template<> ::raftkv::raft::LogEntry* Arena::CreateMaybeMessage<::raftkv::raft::LogEntry>(Arena*);
template<> ::raftkv::raft::RaftPersistState* Arena::CreateMaybeMessage<::raftkv::raft::RaftPersistState>(Arena*);
template<> ::raftkv::raft::RequestVoteReply* Arena::CreateMaybeMessage<::raftkv::raft::RequestVoteReply>(Arena*);
template<> ::raftkv::raft::RequestVoteRequest* Arena::CreateMaybeMessage<::raftkv::raft::RequestVoteRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace raftkv {
namespace raft {

// ===================================================================

class LogEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.LogEntry) */ {
 public:
  LogEntry();
  virtual ~LogEntry();

  LogEntry(const LogEntry& from);

  inline LogEntry& operator=(const LogEntry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LogEntry(LogEntry&& from) noexcept
    : LogEntry() {
    *this = ::std::move(from);
  }

  inline LogEntry& operator=(LogEntry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LogEntry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogEntry* internal_default_instance() {
    return reinterpret_cast<const LogEntry*>(
               &_LogEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(LogEntry* other);
  friend void swap(LogEntry& a, LogEntry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LogEntry* New() const final {
    return CreateMaybeMessage<LogEntry>(NULL);
  }

  LogEntry* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LogEntry>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LogEntry& from);
  void MergeFrom(const LogEntry& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes command = 1;
  void clear_command();
  static const int kCommandFieldNumber = 1;
  const ::std::string& command() const;
  void set_command(const ::std::string& value);
  #if LANG_CXX11
  void set_command(::std::string&& value);
  #endif
  void set_command(const char* value);
  void set_command(const void* value, size_t size);
  ::std::string* mutable_command();
  ::std::string* release_command();
  void set_allocated_command(::std::string* command);

  // int32 term = 2;
  void clear_term();
  static const int kTermFieldNumber = 2;
  ::google::protobuf::int32 term() const;
  void set_term(::google::protobuf::int32 value);

  // int32 index = 3;
  void clear_index();
  static const int kIndexFieldNumber = 3;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.LogEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr command_;
  ::google::protobuf::int32 term_;
  ::google::protobuf::int32 index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AppendEntriesRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.AppendEntriesRequest) */ {
 public:
  AppendEntriesRequest();
  virtual ~AppendEntriesRequest();

  AppendEntriesRequest(const AppendEntriesRequest& from);

  inline AppendEntriesRequest& operator=(const AppendEntriesRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AppendEntriesRequest(AppendEntriesRequest&& from) noexcept
    : AppendEntriesRequest() {
    *this = ::std::move(from);
  }

  inline AppendEntriesRequest& operator=(AppendEntriesRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AppendEntriesRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AppendEntriesRequest* internal_default_instance() {
    return reinterpret_cast<const AppendEntriesRequest*>(
               &_AppendEntriesRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(AppendEntriesRequest* other);
  friend void swap(AppendEntriesRequest& a, AppendEntriesRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AppendEntriesRequest* New() const final {
    return CreateMaybeMessage<AppendEntriesRequest>(NULL);
  }

  AppendEntriesRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AppendEntriesRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AppendEntriesRequest& from);
  void MergeFrom(const AppendEntriesRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppendEntriesRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .raftkv.raft.LogEntry entries = 5;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 5;
  ::raftkv::raft::LogEntry* mutable_entries(int index);
  ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry >*
      mutable_entries();
  const ::raftkv::raft::LogEntry& entries(int index) const;
  ::raftkv::raft::LogEntry* add_entries();
  const ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry >&
      entries() const;

  // int32 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::int32 term() const;
  void set_term(::google::protobuf::int32 value);

  // int32 leader_id = 2;
  void clear_leader_id();
  static const int kLeaderIdFieldNumber = 2;
  ::google::protobuf::int32 leader_id() const;
  void set_leader_id(::google::protobuf::int32 value);

  // int32 prev_log_index = 3;
  void clear_prev_log_index();
  static const int kPrevLogIndexFieldNumber = 3;
  ::google::protobuf::int32 prev_log_index() const;
  void set_prev_log_index(::google::protobuf::int32 value);

  // int32 prev_log_term = 4;
  void clear_prev_log_term();
  static const int kPrevLogTermFieldNumber = 4;
  ::google::protobuf::int32 prev_log_term() const;
  void set_prev_log_term(::google::protobuf::int32 value);

  // int32 leader_commit = 6;
  void clear_leader_commit();
  static const int kLeaderCommitFieldNumber = 6;
  ::google::protobuf::int32 leader_commit() const;
  void set_leader_commit(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.AppendEntriesRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry > entries_;
  ::google::protobuf::int32 term_;
  ::google::protobuf::int32 leader_id_;
  ::google::protobuf::int32 prev_log_index_;
  ::google::protobuf::int32 prev_log_term_;
  ::google::protobuf::int32 leader_commit_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AppendEntriesReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.AppendEntriesReply) */ {
 public:
  AppendEntriesReply();
  virtual ~AppendEntriesReply();

  AppendEntriesReply(const AppendEntriesReply& from);

  inline AppendEntriesReply& operator=(const AppendEntriesReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AppendEntriesReply(AppendEntriesReply&& from) noexcept
    : AppendEntriesReply() {
    *this = ::std::move(from);
  }

  inline AppendEntriesReply& operator=(AppendEntriesReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AppendEntriesReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AppendEntriesReply* internal_default_instance() {
    return reinterpret_cast<const AppendEntriesReply*>(
               &_AppendEntriesReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(AppendEntriesReply* other);
  friend void swap(AppendEntriesReply& a, AppendEntriesReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AppendEntriesReply* New() const final {
    return CreateMaybeMessage<AppendEntriesReply>(NULL);
  }

  AppendEntriesReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AppendEntriesReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AppendEntriesReply& from);
  void MergeFrom(const AppendEntriesReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AppendEntriesReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::int32 term() const;
  void set_term(::google::protobuf::int32 value);

  // bool success = 2;
  void clear_success();
  static const int kSuccessFieldNumber = 2;
  bool success() const;
  void set_success(bool value);

  // int32 conflict_index = 3;
  void clear_conflict_index();
  static const int kConflictIndexFieldNumber = 3;
  ::google::protobuf::int32 conflict_index() const;
  void set_conflict_index(::google::protobuf::int32 value);

  // int32 conflict_term = 4;
  void clear_conflict_term();
  static const int kConflictTermFieldNumber = 4;
  ::google::protobuf::int32 conflict_term() const;
  void set_conflict_term(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.AppendEntriesReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 term_;
  bool success_;
  ::google::protobuf::int32 conflict_index_;
  ::google::protobuf::int32 conflict_term_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RequestVoteRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.RequestVoteRequest) */ {
 public:
  RequestVoteRequest();
  virtual ~RequestVoteRequest();

  RequestVoteRequest(const RequestVoteRequest& from);

  inline RequestVoteRequest& operator=(const RequestVoteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RequestVoteRequest(RequestVoteRequest&& from) noexcept
    : RequestVoteRequest() {
    *this = ::std::move(from);
  }

  inline RequestVoteRequest& operator=(RequestVoteRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestVoteRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestVoteRequest* internal_default_instance() {
    return reinterpret_cast<const RequestVoteRequest*>(
               &_RequestVoteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(RequestVoteRequest* other);
  friend void swap(RequestVoteRequest& a, RequestVoteRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RequestVoteRequest* New() const final {
    return CreateMaybeMessage<RequestVoteRequest>(NULL);
  }

  RequestVoteRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RequestVoteRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RequestVoteRequest& from);
  void MergeFrom(const RequestVoteRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestVoteRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::int32 term() const;
  void set_term(::google::protobuf::int32 value);

  // int32 candidate_id = 2;
  void clear_candidate_id();
  static const int kCandidateIdFieldNumber = 2;
  ::google::protobuf::int32 candidate_id() const;
  void set_candidate_id(::google::protobuf::int32 value);

  // int32 last_log_index = 3;
  void clear_last_log_index();
  static const int kLastLogIndexFieldNumber = 3;
  ::google::protobuf::int32 last_log_index() const;
  void set_last_log_index(::google::protobuf::int32 value);

  // int32 last_log_term = 4;
  void clear_last_log_term();
  static const int kLastLogTermFieldNumber = 4;
  ::google::protobuf::int32 last_log_term() const;
  void set_last_log_term(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.RequestVoteRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 term_;
  ::google::protobuf::int32 candidate_id_;
  ::google::protobuf::int32 last_log_index_;
  ::google::protobuf::int32 last_log_term_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RequestVoteReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.RequestVoteReply) */ {
 public:
  RequestVoteReply();
  virtual ~RequestVoteReply();

  RequestVoteReply(const RequestVoteReply& from);

  inline RequestVoteReply& operator=(const RequestVoteReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RequestVoteReply(RequestVoteReply&& from) noexcept
    : RequestVoteReply() {
    *this = ::std::move(from);
  }

  inline RequestVoteReply& operator=(RequestVoteReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestVoteReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestVoteReply* internal_default_instance() {
    return reinterpret_cast<const RequestVoteReply*>(
               &_RequestVoteReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(RequestVoteReply* other);
  friend void swap(RequestVoteReply& a, RequestVoteReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RequestVoteReply* New() const final {
    return CreateMaybeMessage<RequestVoteReply>(NULL);
  }

  RequestVoteReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RequestVoteReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RequestVoteReply& from);
  void MergeFrom(const RequestVoteReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestVoteReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::int32 term() const;
  void set_term(::google::protobuf::int32 value);

  // bool vote_granted = 2;
  void clear_vote_granted();
  static const int kVoteGrantedFieldNumber = 2;
  bool vote_granted() const;
  void set_vote_granted(bool value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.RequestVoteReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 term_;
  bool vote_granted_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InstallSnapshotRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.InstallSnapshotRequest) */ {
 public:
  InstallSnapshotRequest();
  virtual ~InstallSnapshotRequest();

  InstallSnapshotRequest(const InstallSnapshotRequest& from);

  inline InstallSnapshotRequest& operator=(const InstallSnapshotRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InstallSnapshotRequest(InstallSnapshotRequest&& from) noexcept
    : InstallSnapshotRequest() {
    *this = ::std::move(from);
  }

  inline InstallSnapshotRequest& operator=(InstallSnapshotRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InstallSnapshotRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InstallSnapshotRequest* internal_default_instance() {
    return reinterpret_cast<const InstallSnapshotRequest*>(
               &_InstallSnapshotRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(InstallSnapshotRequest* other);
  friend void swap(InstallSnapshotRequest& a, InstallSnapshotRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InstallSnapshotRequest* New() const final {
    return CreateMaybeMessage<InstallSnapshotRequest>(NULL);
  }

  InstallSnapshotRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InstallSnapshotRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InstallSnapshotRequest& from);
  void MergeFrom(const InstallSnapshotRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstallSnapshotRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 5;
  void clear_data();
  static const int kDataFieldNumber = 5;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // int32 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::int32 term() const;
  void set_term(::google::protobuf::int32 value);

  // int32 leader_id = 2;
  void clear_leader_id();
  static const int kLeaderIdFieldNumber = 2;
  ::google::protobuf::int32 leader_id() const;
  void set_leader_id(::google::protobuf::int32 value);

  // int32 last_included_index = 3;
  void clear_last_included_index();
  static const int kLastIncludedIndexFieldNumber = 3;
  ::google::protobuf::int32 last_included_index() const;
  void set_last_included_index(::google::protobuf::int32 value);

  // int32 last_included_term = 4;
  void clear_last_included_term();
  static const int kLastIncludedTermFieldNumber = 4;
  ::google::protobuf::int32 last_included_term() const;
  void set_last_included_term(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.InstallSnapshotRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int32 term_;
  ::google::protobuf::int32 leader_id_;
  ::google::protobuf::int32 last_included_index_;
  ::google::protobuf::int32 last_included_term_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InstallSnapshotReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.InstallSnapshotReply) */ {
 public:
  InstallSnapshotReply();
  virtual ~InstallSnapshotReply();

  InstallSnapshotReply(const InstallSnapshotReply& from);

  inline InstallSnapshotReply& operator=(const InstallSnapshotReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InstallSnapshotReply(InstallSnapshotReply&& from) noexcept
    : InstallSnapshotReply() {
    *this = ::std::move(from);
  }

  inline InstallSnapshotReply& operator=(InstallSnapshotReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InstallSnapshotReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InstallSnapshotReply* internal_default_instance() {
    return reinterpret_cast<const InstallSnapshotReply*>(
               &_InstallSnapshotReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(InstallSnapshotReply* other);
  friend void swap(InstallSnapshotReply& a, InstallSnapshotReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InstallSnapshotReply* New() const final {
    return CreateMaybeMessage<InstallSnapshotReply>(NULL);
  }

  InstallSnapshotReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InstallSnapshotReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InstallSnapshotReply& from);
  void MergeFrom(const InstallSnapshotReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstallSnapshotReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::int32 term() const;
  void set_term(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.InstallSnapshotReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 term_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RaftPersistState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.RaftPersistState) */ {
 public:
  RaftPersistState();
  virtual ~RaftPersistState();

  RaftPersistState(const RaftPersistState& from);

  inline RaftPersistState& operator=(const RaftPersistState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RaftPersistState(RaftPersistState&& from) noexcept
    : RaftPersistState() {
    *this = ::std::move(from);
  }

  inline RaftPersistState& operator=(RaftPersistState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RaftPersistState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RaftPersistState* internal_default_instance() {
    return reinterpret_cast<const RaftPersistState*>(
               &_RaftPersistState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(RaftPersistState* other);
  friend void swap(RaftPersistState& a, RaftPersistState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RaftPersistState* New() const final {
    return CreateMaybeMessage<RaftPersistState>(NULL);
  }

  RaftPersistState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RaftPersistState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RaftPersistState& from);
  void MergeFrom(const RaftPersistState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftPersistState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .raftkv.raft.LogEntry logs = 3;
  int logs_size() const;
  void clear_logs();
  static const int kLogsFieldNumber = 3;
  ::raftkv::raft::LogEntry* mutable_logs(int index);
  ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry >*
      mutable_logs();
  const ::raftkv::raft::LogEntry& logs(int index) const;
  ::raftkv::raft::LogEntry* add_logs();
  const ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry >&
      logs() const;

  // int32 current_term = 1;
  void clear_current_term();
  static const int kCurrentTermFieldNumber = 1;
  ::google::protobuf::int32 current_term() const;
  void set_current_term(::google::protobuf::int32 value);

  // int32 voted_for = 2;
  void clear_voted_for();
  static const int kVotedForFieldNumber = 2;
  ::google::protobuf::int32 voted_for() const;
  void set_voted_for(::google::protobuf::int32 value);

  // int32 last_snapshot_index = 4;
  void clear_last_snapshot_index();
  static const int kLastSnapshotIndexFieldNumber = 4;
  ::google::protobuf::int32 last_snapshot_index() const;
  void set_last_snapshot_index(::google::protobuf::int32 value);

  // int32 last_snapshot_term = 5;
  void clear_last_snapshot_term();
  static const int kLastSnapshotTermFieldNumber = 5;
  ::google::protobuf::int32 last_snapshot_term() const;
  void set_last_snapshot_term(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.RaftPersistState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry > logs_;
  ::google::protobuf::int32 current_term_;
  ::google::protobuf::int32 voted_for_;
  ::google::protobuf::int32 last_snapshot_index_;
  ::google::protobuf::int32 last_snapshot_term_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetStatusRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.GetStatusRequest) */ {
 public:
  GetStatusRequest();
  virtual ~GetStatusRequest();

  GetStatusRequest(const GetStatusRequest& from);

  inline GetStatusRequest& operator=(const GetStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetStatusRequest(GetStatusRequest&& from) noexcept
    : GetStatusRequest() {
    *this = ::std::move(from);
  }

  inline GetStatusRequest& operator=(GetStatusRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetStatusRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetStatusRequest* internal_default_instance() {
    return reinterpret_cast<const GetStatusRequest*>(
               &_GetStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(GetStatusRequest* other);
  friend void swap(GetStatusRequest& a, GetStatusRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetStatusRequest* New() const final {
    return CreateMaybeMessage<GetStatusRequest>(NULL);
  }

  GetStatusRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetStatusRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetStatusRequest& from);
  void MergeFrom(const GetStatusRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStatusRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:raftkv.raft.GetStatusRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetStatusReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:raftkv.raft.GetStatusReply) */ {
 public:
  GetStatusReply();
  virtual ~GetStatusReply();

  GetStatusReply(const GetStatusReply& from);

  inline GetStatusReply& operator=(const GetStatusReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetStatusReply(GetStatusReply&& from) noexcept
    : GetStatusReply() {
    *this = ::std::move(from);
  }

  inline GetStatusReply& operator=(GetStatusReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetStatusReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetStatusReply* internal_default_instance() {
    return reinterpret_cast<const GetStatusReply*>(
               &_GetStatusReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(GetStatusReply* other);
  friend void swap(GetStatusReply& a, GetStatusReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetStatusReply* New() const final {
    return CreateMaybeMessage<GetStatusReply>(NULL);
  }

  GetStatusReply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetStatusReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetStatusReply& from);
  void MergeFrom(const GetStatusReply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetStatusReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string role = 3;
  void clear_role();
  static const int kRoleFieldNumber = 3;
  const ::std::string& role() const;
  void set_role(const ::std::string& value);
  #if LANG_CXX11
  void set_role(::std::string&& value);
  #endif
  void set_role(const char* value);
  void set_role(const char* value, size_t size);
  ::std::string* mutable_role();
  ::std::string* release_role();
  void set_allocated_role(::std::string* role);

  // int32 node_id = 1;
  void clear_node_id();
  static const int kNodeIdFieldNumber = 1;
  ::google::protobuf::int32 node_id() const;
  void set_node_id(::google::protobuf::int32 value);

  // int32 term = 2;
  void clear_term();
  static const int kTermFieldNumber = 2;
  ::google::protobuf::int32 term() const;
  void set_term(::google::protobuf::int32 value);

  // int32 last_log_index = 4;
  void clear_last_log_index();
  static const int kLastLogIndexFieldNumber = 4;
  ::google::protobuf::int32 last_log_index() const;
  void set_last_log_index(::google::protobuf::int32 value);

  // int32 commit_index = 5;
  void clear_commit_index();
  static const int kCommitIndexFieldNumber = 5;
  ::google::protobuf::int32 commit_index() const;
  void set_commit_index(::google::protobuf::int32 value);

  // int32 last_applied = 6;
  void clear_last_applied();
  static const int kLastAppliedFieldNumber = 6;
  ::google::protobuf::int32 last_applied() const;
  void set_last_applied(::google::protobuf::int32 value);

  // int32 last_snapshot_index = 7;
  void clear_last_snapshot_index();
  static const int kLastSnapshotIndexFieldNumber = 7;
  ::google::protobuf::int32 last_snapshot_index() const;
  void set_last_snapshot_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:raftkv.raft.GetStatusReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr role_;
  ::google::protobuf::int32 node_id_;
  ::google::protobuf::int32 term_;
  ::google::protobuf::int32 last_log_index_;
  ::google::protobuf::int32 commit_index_;
  ::google::protobuf::int32 last_applied_;
  ::google::protobuf::int32 last_snapshot_index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_raft_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogEntry

// bytes command = 1;
inline void LogEntry::clear_command() {
  command_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LogEntry::command() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.LogEntry.command)
  return command_.GetNoArena();
}
inline void LogEntry::set_command(const ::std::string& value) {
  
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raftkv.raft.LogEntry.command)
}
#if LANG_CXX11
inline void LogEntry::set_command(::std::string&& value) {
  
  command_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raftkv.raft.LogEntry.command)
}
#endif
inline void LogEntry::set_command(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raftkv.raft.LogEntry.command)
}
inline void LogEntry::set_command(const void* value, size_t size) {
  
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raftkv.raft.LogEntry.command)
}
inline ::std::string* LogEntry::mutable_command() {
  
  // @@protoc_insertion_point(field_mutable:raftkv.raft.LogEntry.command)
  return command_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogEntry::release_command() {
  // @@protoc_insertion_point(field_release:raftkv.raft.LogEntry.command)
  
  return command_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogEntry::set_allocated_command(::std::string* command) {
  if (command != NULL) {
    
  } else {
    
  }
  command_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), command);
  // @@protoc_insertion_point(field_set_allocated:raftkv.raft.LogEntry.command)
}

// int32 term = 2;
inline void LogEntry::clear_term() {
  term_ = 0;
}
inline ::google::protobuf::int32 LogEntry::term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.LogEntry.term)
  return term_;
}
inline void LogEntry::set_term(::google::protobuf::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.LogEntry.term)
}

// int32 index = 3;
inline void LogEntry::clear_index() {
  index_ = 0;
}
inline ::google::protobuf::int32 LogEntry::index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.LogEntry.index)
  return index_;
}
inline void LogEntry::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.LogEntry.index)
}

// -------------------------------------------------------------------

// AppendEntriesRequest

// int32 term = 1;
inline void AppendEntriesRequest::clear_term() {
  term_ = 0;
}
inline ::google::protobuf::int32 AppendEntriesRequest::term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesRequest.term)
  return term_;
}
inline void AppendEntriesRequest::set_term(::google::protobuf::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesRequest.term)
}

// int32 leader_id = 2;
inline void AppendEntriesRequest::clear_leader_id() {
  leader_id_ = 0;
}
inline ::google::protobuf::int32 AppendEntriesRequest::leader_id() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesRequest.leader_id)
  return leader_id_;
}
inline void AppendEntriesRequest::set_leader_id(::google::protobuf::int32 value) {
  
  leader_id_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesRequest.leader_id)
}

// int32 prev_log_index = 3;
inline void AppendEntriesRequest::clear_prev_log_index() {
  prev_log_index_ = 0;
}
inline ::google::protobuf::int32 AppendEntriesRequest::prev_log_index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesRequest.prev_log_index)
  return prev_log_index_;
}
inline void AppendEntriesRequest::set_prev_log_index(::google::protobuf::int32 value) {
  
  prev_log_index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesRequest.prev_log_index)
}

// int32 prev_log_term = 4;
inline void AppendEntriesRequest::clear_prev_log_term() {
  prev_log_term_ = 0;
}
inline ::google::protobuf::int32 AppendEntriesRequest::prev_log_term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesRequest.prev_log_term)
  return prev_log_term_;
}
inline void AppendEntriesRequest::set_prev_log_term(::google::protobuf::int32 value) {
  
  prev_log_term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesRequest.prev_log_term)
}

// repeated .raftkv.raft.LogEntry entries = 5;
inline int AppendEntriesRequest::entries_size() const {
  return entries_.size();
}
inline void AppendEntriesRequest::clear_entries() {
  entries_.Clear();
}
inline ::raftkv::raft::LogEntry* AppendEntriesRequest::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:raftkv.raft.AppendEntriesRequest.entries)
  return entries_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry >*
AppendEntriesRequest::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:raftkv.raft.AppendEntriesRequest.entries)
  return &entries_;
}
inline const ::raftkv::raft::LogEntry& AppendEntriesRequest::entries(int index) const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesRequest.entries)
  return entries_.Get(index);
}
inline ::raftkv::raft::LogEntry* AppendEntriesRequest::add_entries() {
  // @@protoc_insertion_point(field_add:raftkv.raft.AppendEntriesRequest.entries)
  return entries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry >&
AppendEntriesRequest::entries() const {
  // @@protoc_insertion_point(field_list:raftkv.raft.AppendEntriesRequest.entries)
  return entries_;
}

// int32 leader_commit = 6;
inline void AppendEntriesRequest::clear_leader_commit() {
  leader_commit_ = 0;
}
inline ::google::protobuf::int32 AppendEntriesRequest::leader_commit() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesRequest.leader_commit)
  return leader_commit_;
}
inline void AppendEntriesRequest::set_leader_commit(::google::protobuf::int32 value) {
  
  leader_commit_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesRequest.leader_commit)
}

// -------------------------------------------------------------------

// AppendEntriesReply

// int32 term = 1;
inline void AppendEntriesReply::clear_term() {
  term_ = 0;
}
inline ::google::protobuf::int32 AppendEntriesReply::term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesReply.term)
  return term_;
}
inline void AppendEntriesReply::set_term(::google::protobuf::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesReply.term)
}

// bool success = 2;
inline void AppendEntriesReply::clear_success() {
  success_ = false;
}
inline bool AppendEntriesReply::success() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesReply.success)
  return success_;
}
inline void AppendEntriesReply::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesReply.success)
}

// int32 conflict_index = 3;
inline void AppendEntriesReply::clear_conflict_index() {
  conflict_index_ = 0;
}
inline ::google::protobuf::int32 AppendEntriesReply::conflict_index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesReply.conflict_index)
  return conflict_index_;
}
inline void AppendEntriesReply::set_conflict_index(::google::protobuf::int32 value) {
  
  conflict_index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesReply.conflict_index)
}

// int32 conflict_term = 4;
inline void AppendEntriesReply::clear_conflict_term() {
  conflict_term_ = 0;
}
inline ::google::protobuf::int32 AppendEntriesReply::conflict_term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.AppendEntriesReply.conflict_term)
  return conflict_term_;
}
inline void AppendEntriesReply::set_conflict_term(::google::protobuf::int32 value) {
  
  conflict_term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.AppendEntriesReply.conflict_term)
}

// -------------------------------------------------------------------

// RequestVoteRequest

// int32 term = 1;
inline void RequestVoteRequest::clear_term() {
  term_ = 0;
}
inline ::google::protobuf::int32 RequestVoteRequest::term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RequestVoteRequest.term)
  return term_;
}
inline void RequestVoteRequest::set_term(::google::protobuf::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RequestVoteRequest.term)
}

// int32 candidate_id = 2;
inline void RequestVoteRequest::clear_candidate_id() {
  candidate_id_ = 0;
}
inline ::google::protobuf::int32 RequestVoteRequest::candidate_id() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RequestVoteRequest.candidate_id)
  return candidate_id_;
}
inline void RequestVoteRequest::set_candidate_id(::google::protobuf::int32 value) {
  
  candidate_id_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RequestVoteRequest.candidate_id)
}

// int32 last_log_index = 3;
inline void RequestVoteRequest::clear_last_log_index() {
  last_log_index_ = 0;
}
inline ::google::protobuf::int32 RequestVoteRequest::last_log_index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RequestVoteRequest.last_log_index)
  return last_log_index_;
}
inline void RequestVoteRequest::set_last_log_index(::google::protobuf::int32 value) {
  
  last_log_index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RequestVoteRequest.last_log_index)
}

// int32 last_log_term = 4;
inline void RequestVoteRequest::clear_last_log_term() {
  last_log_term_ = 0;
}
inline ::google::protobuf::int32 RequestVoteRequest::last_log_term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RequestVoteRequest.last_log_term)
  return last_log_term_;
}
inline void RequestVoteRequest::set_last_log_term(::google::protobuf::int32 value) {
  
  last_log_term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RequestVoteRequest.last_log_term)
}

// -------------------------------------------------------------------

// RequestVoteReply

// int32 term = 1;
inline void RequestVoteReply::clear_term() {
  term_ = 0;
}
inline ::google::protobuf::int32 RequestVoteReply::term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RequestVoteReply.term)
  return term_;
}
inline void RequestVoteReply::set_term(::google::protobuf::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RequestVoteReply.term)
}

// bool vote_granted = 2;
inline void RequestVoteReply::clear_vote_granted() {
  vote_granted_ = false;
}
inline bool RequestVoteReply::vote_granted() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RequestVoteReply.vote_granted)
  return vote_granted_;
}
inline void RequestVoteReply::set_vote_granted(bool value) {
  
  vote_granted_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RequestVoteReply.vote_granted)
}

// -------------------------------------------------------------------

// InstallSnapshotRequest

// int32 term = 1;
inline void InstallSnapshotRequest::clear_term() {
  term_ = 0;
}
inline ::google::protobuf::int32 InstallSnapshotRequest::term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.InstallSnapshotRequest.term)
  return term_;
}
inline void InstallSnapshotRequest::set_term(::google::protobuf::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.InstallSnapshotRequest.term)
}

// int32 leader_id = 2;
inline void InstallSnapshotRequest::clear_leader_id() {
  leader_id_ = 0;
}
inline ::google::protobuf::int32 InstallSnapshotRequest::leader_id() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.InstallSnapshotRequest.leader_id)
  return leader_id_;
}
inline void InstallSnapshotRequest::set_leader_id(::google::protobuf::int32 value) {
  
  leader_id_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.InstallSnapshotRequest.leader_id)
}

// int32 last_included_index = 3;
inline void InstallSnapshotRequest::clear_last_included_index() {
  last_included_index_ = 0;
}
inline ::google::protobuf::int32 InstallSnapshotRequest::last_included_index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.InstallSnapshotRequest.last_included_index)
  return last_included_index_;
}
inline void InstallSnapshotRequest::set_last_included_index(::google::protobuf::int32 value) {
  
  last_included_index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.InstallSnapshotRequest.last_included_index)
}

// int32 last_included_term = 4;
inline void InstallSnapshotRequest::clear_last_included_term() {
  last_included_term_ = 0;
}
inline ::google::protobuf::int32 InstallSnapshotRequest::last_included_term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.InstallSnapshotRequest.last_included_term)
  return last_included_term_;
}
inline void InstallSnapshotRequest::set_last_included_term(::google::protobuf::int32 value) {
  
  last_included_term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.InstallSnapshotRequest.last_included_term)
}

// bytes data = 5;
inline void InstallSnapshotRequest::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InstallSnapshotRequest::data() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.InstallSnapshotRequest.data)
  return data_.GetNoArena();
}
inline void InstallSnapshotRequest::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raftkv.raft.InstallSnapshotRequest.data)
}
#if LANG_CXX11
inline void InstallSnapshotRequest::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raftkv.raft.InstallSnapshotRequest.data)
}
#endif
inline void InstallSnapshotRequest::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raftkv.raft.InstallSnapshotRequest.data)
}
inline void InstallSnapshotRequest::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raftkv.raft.InstallSnapshotRequest.data)
}
inline ::std::string* InstallSnapshotRequest::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:raftkv.raft.InstallSnapshotRequest.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InstallSnapshotRequest::release_data() {
  // @@protoc_insertion_point(field_release:raftkv.raft.InstallSnapshotRequest.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InstallSnapshotRequest::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:raftkv.raft.InstallSnapshotRequest.data)
}

// -------------------------------------------------------------------

// InstallSnapshotReply

// int32 term = 1;
inline void InstallSnapshotReply::clear_term() {
  term_ = 0;
}
inline ::google::protobuf::int32 InstallSnapshotReply::term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.InstallSnapshotReply.term)
  return term_;
}
inline void InstallSnapshotReply::set_term(::google::protobuf::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.InstallSnapshotReply.term)
}

// -------------------------------------------------------------------

// RaftPersistState

// int32 current_term = 1;
inline void RaftPersistState::clear_current_term() {
  current_term_ = 0;
}
inline ::google::protobuf::int32 RaftPersistState::current_term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RaftPersistState.current_term)
  return current_term_;
}
inline void RaftPersistState::set_current_term(::google::protobuf::int32 value) {
  
  current_term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RaftPersistState.current_term)
}

// int32 voted_for = 2;
inline void RaftPersistState::clear_voted_for() {
  voted_for_ = 0;
}
inline ::google::protobuf::int32 RaftPersistState::voted_for() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RaftPersistState.voted_for)
  return voted_for_;
}
inline void RaftPersistState::set_voted_for(::google::protobuf::int32 value) {
  
  voted_for_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RaftPersistState.voted_for)
}

// repeated .raftkv.raft.LogEntry logs = 3;
inline int RaftPersistState::logs_size() const {
  return logs_.size();
}
inline void RaftPersistState::clear_logs() {
  logs_.Clear();
}
inline ::raftkv::raft::LogEntry* RaftPersistState::mutable_logs(int index) {
  // @@protoc_insertion_point(field_mutable:raftkv.raft.RaftPersistState.logs)
  return logs_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry >*
RaftPersistState::mutable_logs() {
  // @@protoc_insertion_point(field_mutable_list:raftkv.raft.RaftPersistState.logs)
  return &logs_;
}
inline const ::raftkv::raft::LogEntry& RaftPersistState::logs(int index) const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RaftPersistState.logs)
  return logs_.Get(index);
}
inline ::raftkv::raft::LogEntry* RaftPersistState::add_logs() {
  // @@protoc_insertion_point(field_add:raftkv.raft.RaftPersistState.logs)
  return logs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::raftkv::raft::LogEntry >&
RaftPersistState::logs() const {
  // @@protoc_insertion_point(field_list:raftkv.raft.RaftPersistState.logs)
  return logs_;
}

// int32 last_snapshot_index = 4;
inline void RaftPersistState::clear_last_snapshot_index() {
  last_snapshot_index_ = 0;
}
inline ::google::protobuf::int32 RaftPersistState::last_snapshot_index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RaftPersistState.last_snapshot_index)
  return last_snapshot_index_;
}
inline void RaftPersistState::set_last_snapshot_index(::google::protobuf::int32 value) {
  
  last_snapshot_index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RaftPersistState.last_snapshot_index)
}

// int32 last_snapshot_term = 5;
inline void RaftPersistState::clear_last_snapshot_term() {
  last_snapshot_term_ = 0;
}
inline ::google::protobuf::int32 RaftPersistState::last_snapshot_term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.RaftPersistState.last_snapshot_term)
  return last_snapshot_term_;
}
inline void RaftPersistState::set_last_snapshot_term(::google::protobuf::int32 value) {
  
  last_snapshot_term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.RaftPersistState.last_snapshot_term)
}

// -------------------------------------------------------------------

// GetStatusRequest

// -------------------------------------------------------------------

// GetStatusReply

// int32 node_id = 1;
inline void GetStatusReply::clear_node_id() {
  node_id_ = 0;
}
inline ::google::protobuf::int32 GetStatusReply::node_id() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.GetStatusReply.node_id)
  return node_id_;
}
inline void GetStatusReply::set_node_id(::google::protobuf::int32 value) {
  
  node_id_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.GetStatusReply.node_id)
}

// int32 term = 2;
inline void GetStatusReply::clear_term() {
  term_ = 0;
}
inline ::google::protobuf::int32 GetStatusReply::term() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.GetStatusReply.term)
  return term_;
}
inline void GetStatusReply::set_term(::google::protobuf::int32 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.GetStatusReply.term)
}

// string role = 3;
inline void GetStatusReply::clear_role() {
  role_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetStatusReply::role() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.GetStatusReply.role)
  return role_.GetNoArena();
}
inline void GetStatusReply::set_role(const ::std::string& value) {
  
  role_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:raftkv.raft.GetStatusReply.role)
}
#if LANG_CXX11
inline void GetStatusReply::set_role(::std::string&& value) {
  
  role_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:raftkv.raft.GetStatusReply.role)
}
#endif
inline void GetStatusReply::set_role(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  role_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:raftkv.raft.GetStatusReply.role)
}
inline void GetStatusReply::set_role(const char* value, size_t size) {
  
  role_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:raftkv.raft.GetStatusReply.role)
}
inline ::std::string* GetStatusReply::mutable_role() {
  
  // @@protoc_insertion_point(field_mutable:raftkv.raft.GetStatusReply.role)
  return role_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetStatusReply::release_role() {
  // @@protoc_insertion_point(field_release:raftkv.raft.GetStatusReply.role)
  
  return role_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetStatusReply::set_allocated_role(::std::string* role) {
  if (role != NULL) {
    
  } else {
    
  }
  role_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), role);
  // @@protoc_insertion_point(field_set_allocated:raftkv.raft.GetStatusReply.role)
}

// int32 last_log_index = 4;
inline void GetStatusReply::clear_last_log_index() {
  last_log_index_ = 0;
}
inline ::google::protobuf::int32 GetStatusReply::last_log_index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.GetStatusReply.last_log_index)
  return last_log_index_;
}
inline void GetStatusReply::set_last_log_index(::google::protobuf::int32 value) {
  
  last_log_index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.GetStatusReply.last_log_index)
}

// int32 commit_index = 5;
inline void GetStatusReply::clear_commit_index() {
  commit_index_ = 0;
}
inline ::google::protobuf::int32 GetStatusReply::commit_index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.GetStatusReply.commit_index)
  return commit_index_;
}
inline void GetStatusReply::set_commit_index(::google::protobuf::int32 value) {
  
  commit_index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.GetStatusReply.commit_index)
}

// int32 last_applied = 6;
inline void GetStatusReply::clear_last_applied() {
  last_applied_ = 0;
}
inline ::google::protobuf::int32 GetStatusReply::last_applied() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.GetStatusReply.last_applied)
  return last_applied_;
}
inline void GetStatusReply::set_last_applied(::google::protobuf::int32 value) {
  
  last_applied_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.GetStatusReply.last_applied)
}

// int32 last_snapshot_index = 7;
inline void GetStatusReply::clear_last_snapshot_index() {
  last_snapshot_index_ = 0;
}
inline ::google::protobuf::int32 GetStatusReply::last_snapshot_index() const {
  // @@protoc_insertion_point(field_get:raftkv.raft.GetStatusReply.last_snapshot_index)
  return last_snapshot_index_;
}
inline void GetStatusReply::set_last_snapshot_index(::google::protobuf::int32 value) {
  
  last_snapshot_index_ = value;
  // @@protoc_insertion_point(field_set:raftkv.raft.GetStatusReply.last_snapshot_index)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace raft
}  // namespace raftkv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_raft_2eproto
