// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: raft.proto

#include "raft.pb.h"
#include "raft.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace raftkv {
namespace raft {

static const char* RaftService_method_names[] = {
  "/raftkv.raft.RaftService/AppendEntries",
  "/raftkv.raft.RaftService/RequestVote",
  "/raftkv.raft.RaftService/InstallSnapshot",
  "/raftkv.raft.RaftService/GetStatus",
};

std::unique_ptr< RaftService::Stub> RaftService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RaftService::Stub> stub(new RaftService::Stub(channel));
  return stub;
}

RaftService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_AppendEntries_(RaftService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RequestVote_(RaftService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InstallSnapshot_(RaftService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStatus_(RaftService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RaftService::Stub::AppendEntries(::grpc::ClientContext* context, const ::raftkv::raft::AppendEntriesRequest& request, ::raftkv::raft::AppendEntriesReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_AppendEntries_, context, request, response);
}

void RaftService::Stub::experimental_async::AppendEntries(::grpc::ClientContext* context, const ::raftkv::raft::AppendEntriesRequest* request, ::raftkv::raft::AppendEntriesReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_AppendEntries_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::raftkv::raft::AppendEntriesReply>* RaftService::Stub::AsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raftkv::raft::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::raftkv::raft::AppendEntriesReply>::Create(channel_.get(), cq, rpcmethod_AppendEntries_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::raftkv::raft::AppendEntriesReply>* RaftService::Stub::PrepareAsyncAppendEntriesRaw(::grpc::ClientContext* context, const ::raftkv::raft::AppendEntriesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::raftkv::raft::AppendEntriesReply>::Create(channel_.get(), cq, rpcmethod_AppendEntries_, context, request, false);
}

::grpc::Status RaftService::Stub::RequestVote(::grpc::ClientContext* context, const ::raftkv::raft::RequestVoteRequest& request, ::raftkv::raft::RequestVoteReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RequestVote_, context, request, response);
}

void RaftService::Stub::experimental_async::RequestVote(::grpc::ClientContext* context, const ::raftkv::raft::RequestVoteRequest* request, ::raftkv::raft::RequestVoteReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RequestVote_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::raftkv::raft::RequestVoteReply>* RaftService::Stub::AsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raftkv::raft::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::raftkv::raft::RequestVoteReply>::Create(channel_.get(), cq, rpcmethod_RequestVote_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::raftkv::raft::RequestVoteReply>* RaftService::Stub::PrepareAsyncRequestVoteRaw(::grpc::ClientContext* context, const ::raftkv::raft::RequestVoteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::raftkv::raft::RequestVoteReply>::Create(channel_.get(), cq, rpcmethod_RequestVote_, context, request, false);
}

::grpc::Status RaftService::Stub::InstallSnapshot(::grpc::ClientContext* context, const ::raftkv::raft::InstallSnapshotRequest& request, ::raftkv::raft::InstallSnapshotReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_InstallSnapshot_, context, request, response);
}

void RaftService::Stub::experimental_async::InstallSnapshot(::grpc::ClientContext* context, const ::raftkv::raft::InstallSnapshotRequest* request, ::raftkv::raft::InstallSnapshotReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_InstallSnapshot_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::raftkv::raft::InstallSnapshotReply>* RaftService::Stub::AsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raftkv::raft::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::raftkv::raft::InstallSnapshotReply>::Create(channel_.get(), cq, rpcmethod_InstallSnapshot_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::raftkv::raft::InstallSnapshotReply>* RaftService::Stub::PrepareAsyncInstallSnapshotRaw(::grpc::ClientContext* context, const ::raftkv::raft::InstallSnapshotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::raftkv::raft::InstallSnapshotReply>::Create(channel_.get(), cq, rpcmethod_InstallSnapshot_, context, request, false);
}

::grpc::Status RaftService::Stub::GetStatus(::grpc::ClientContext* context, const ::raftkv::raft::GetStatusRequest& request, ::raftkv::raft::GetStatusReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetStatus_, context, request, response);
}

void RaftService::Stub::experimental_async::GetStatus(::grpc::ClientContext* context, const ::raftkv::raft::GetStatusRequest* request, ::raftkv::raft::GetStatusReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::raftkv::raft::GetStatusReply>* RaftService::Stub::AsyncGetStatusRaw(::grpc::ClientContext* context, const ::raftkv::raft::GetStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::raftkv::raft::GetStatusReply>::Create(channel_.get(), cq, rpcmethod_GetStatus_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::raftkv::raft::GetStatusReply>* RaftService::Stub::PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::raftkv::raft::GetStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::raftkv::raft::GetStatusReply>::Create(channel_.get(), cq, rpcmethod_GetStatus_, context, request, false);
}

RaftService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftService::Service, ::raftkv::raft::AppendEntriesRequest, ::raftkv::raft::AppendEntriesReply>(
          std::mem_fn(&RaftService::Service::AppendEntries), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftService::Service, ::raftkv::raft::RequestVoteRequest, ::raftkv::raft::RequestVoteReply>(
          std::mem_fn(&RaftService::Service::RequestVote), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftService::Service, ::raftkv::raft::InstallSnapshotRequest, ::raftkv::raft::InstallSnapshotReply>(
          std::mem_fn(&RaftService::Service::InstallSnapshot), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RaftService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RaftService::Service, ::raftkv::raft::GetStatusRequest, ::raftkv::raft::GetStatusReply>(
          std::mem_fn(&RaftService::Service::GetStatus), this)));
}

RaftService::Service::~Service() {
}

::grpc::Status RaftService::Service::AppendEntries(::grpc::ServerContext* context, const ::raftkv::raft::AppendEntriesRequest* request, ::raftkv::raft::AppendEntriesReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftService::Service::RequestVote(::grpc::ServerContext* context, const ::raftkv::raft::RequestVoteRequest* request, ::raftkv::raft::RequestVoteReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftService::Service::InstallSnapshot(::grpc::ServerContext* context, const ::raftkv::raft::InstallSnapshotRequest* request, ::raftkv::raft::InstallSnapshotReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RaftService::Service::GetStatus(::grpc::ServerContext* context, const ::raftkv::raft::GetStatusRequest* request, ::raftkv::raft::GetStatusReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace raftkv
}  // namespace raft

